# Some logic requires that words only be in one category. 
# Might get weird leaderboard behavior if that isn't true.

# PDT words borrowed from http://www.persondothing.com/

EASY_PDT_WORDS = [
"object",
"bat",
"soldier",
"ship",
"pan",
"bug",
"lab",
"field",
"mug",
"iron",
"clock",
"switch",
"skyscraper",
"alarm",
"bed",
"shop",
"ambulance",
"hole",
"spine",
"soul",
"snowman",
"forest",
"police",
"diamond",
"superhero",
"pipe",
"screen",
"tail",
"itch",
"beach",
"cactus",
"compass",
"tourist",
"blindfold",
"vein",
"submarine",
"backpack",
"cage",
"salad",
"birth",
"contact",
"garage",
"wine",
"license",
"mask",
"pray",
"target",
"reflect",
"blood",
"farmer",
"attic",
"explore",
"melt",
"rope",
"share",
"campfire",
"mermaid",
"sailor",
"retire",
"bottle",
"brave",
"bridge",
"broken",
"bus",
"camera",
"candle",
"cell",
"conversation",
"propose",
"cremate",
"outbreak",
"caffeine",
"bread",
"dance",
"honeymoon",
"vulture",
"soap",
"homesick",
"applaud",
"mirage",
"doctor",
"knit",
"insulation",
"reporter",
"drown",
"downtown",
"dream",
"embarassed",
"detour",
"sword",
"cookie",
"spoil",
"chill",
"fur",
"escape",
"carpool",
"postcard",
"hallucinate",
"nurse",
"bikini",
"safari"
]

   
MEDIUM_PDT_WORDS = [
"hood",
"scorpion",
"crane",
"charge",
"ninja",
"dice",
"ring",
"ruler",
"bank",
"court",
"hotel",
"mail",
"washer",
"bark",
"plastic",
"concert",
"capital",
"sink",
"accident",
"spell",
"laser",
"band",
"angel",
"slug",
"dragon",
"march",
"temple",
"board",
"wind",
"mass",
"comic",
"centaur",
"robot",
"baseball",
"bat",
"slip",
"tag",
"bow",
"sundae",
"growl",
"slide",
"intersection",
"tape",
"sale",
"trapdoor",
"punch",
"bell",
"mosquito",
"blush",
"airbag",
"aquarium",
"pharmacy",
"blink",
"hibernate",
"razor",
"surf",
"adopt",
"record",
"birthday",
"chain",
"bribe",
"genie",
"pimple",
"referee",
"juggle",
"vacuum",
"grenade",
"crawl",
"tunnel",
"bruise",
"bubble",
"button",
"casino",
"club",
"computer",
"crash",
"cruise",
"crumb",
"snorkel",
"curtain",
"hail",
"tiara",
"birthmark",
"deadline",
"microwave",
"dentist",
"seatbelt",
"lighthouse",
"cavity",
"desk",
"jewelry",
"auction",
"deliver",
"environmentalism",
"hook",
"mannequin",
"goggles",
"hollow",
"hijack"
]

HARD_PDT_WORDS = [
"phoenix",
"parachute",
"note",
"luck",
"code",
"contract",
"balance",
"battery",
"degree",
"hitchhike",
"oasis",
"infinity",
"invade",
"stutter",
"interpreter",
"radar",
"inflation",
"hypnotize",
"architect",
"bait",
"tangle",
"hiccup",
"maze",
"nun",
"monopoly",
"paperclip",
"daydream",
"bet",
"stamp",
"turbulence",
"mutiny",
"porcupine",
"tackle",
"blur",
"period",
"circus",
"clown",
"cough",
"harpoon",
"bowling",
"download",
"headquarters",
"meltdown",
"stained",
"reef",
"dimple",
"flexible",
"dominoes",
"rhyme",
"echo",
"bartender",
"hourglass",
"fragile",
"homepage",
"hurricane",
"matador",
"escalator",
"frosting",
"fishbowl",
"scroll",
"choir",
"manicure",
"filter",
"chart",
"prove",
"dungeon",
"swerve",
"scan",
"finger",
"moat",
"fallout",
"gong",
"trace",
"salary",
"rotate",
"manhole",
"guess",
"ribbon",
"spray",
"flush",
"system",
"strike",
"pearl",
"cocoon",
"earthquake",
"subtract",
"burp",
"unicycle",
"budget",
"equator",
"turtle",
"duel",
"curb",
"bingo",
"laboratory",
"even",
"interest",
"napkin",
"faint",
"rip"
]

PDT_WORDS = [
'Audit',
'Naive',
'Explain',
'Harmony',
'Surface',
'Endure',
'Reform',
'Declare',
'Philosophy',
'Lucrative',
'Slogan',
'Deny',
'Torture',
'Dignity',
'Notice',
'Complex',
'Indulgent',
'Permission',
'Nervous',
'Suspicious',
'Conspiracy',
'Cell',
'Summon',
'Significant',
'Observation',
'Instant',
'Department',
'Vouch',
'Risk',
'Ridiculous',
'Disturb',
'Examination',
'Astonished',
'Attitude',
'Personality',
'Remittance',
'Armrest',
'Crunchy',
'Helpless',
'Attention',
'Adequate',
'Purpose',
'Despair',
'Sinking',
'Flattery',
'Charming',
'Prophecy',
'Scene',
'Password',
'Current',
'Finger',
'Thumb',
'Innocence',
'Conservative',
'Poster',
'Answer',
'Certain',
'Admit',
'Acceptance',
'Exit',
'Peanut',
'Welcome',
'Instructions',
'Delusion',
'Burden',
'Explosion',
'Famous',
'Magic',
'Kitchen',
'Syndrome',
'Breakdown',
'Trainee',
'Corridor',
'Experience',
'Confidence',
'Serious',
'Apprentice',
'Tour',
'Reluctant',
'Phase',
'Emotional',
'Dedication',
'Introduction',
'Pressure',
'Responsibility',
'Connection',
'Escape',
'Finish',
'Absurd',
'Warning',
'Dancing',
'Reward',
'Miracle',
'Prestige',
'Filter',
'Final',
'Idiot',
'Familiar',
'Intuition',
'Disgrace',
'Frozen',
'Motivation',
'Opposite',
'Decision',
'Selfish',
'Environment',
'Stress',
'Discipline',
'Bottle',
'Admire',
'Available',
'Punchable',
'Adorable',
'Rage',
'Enemy',
'Standard',
'Surprise',
'Duty',
'Tyrant',
'Rebel',
'Desire',
'Theory',
'Accident',
'Method',
'Temptation',
'Icon',
'Emergency',
'Rejection',
'Title',
'Gesture',
'Influence',
'Spiritual',
'Conversation',
'Mild',
'Cousin',
'Special',
'Freedom',
'Competition',
'Demanding',
'Unbearable',
'Belief',
'Convince',
'Sudden',
'Obvious',
'Direction',
'Button',
'Original',
'Obscure',
'Despise',
'Calculation',
'Inspiration',
'Talent',
'Abstract',
'Spectator',
'Literally',
'Exchange',
'Immoral',
'Balance',
'Defense',
'Cramped',
'Severe',
'Routine',
'Convenient',
'Cautious',
'Vain',
'Tender',
'Eager',
'Excessive',
'Mirror',
'Portrait',
'Expedition',
'Encourage',
'Habit',
'Repeat',
'Hygienic',
'Barbarian',
'Cinder',
'Ambition',
'Delicate',
'Ceremony',
'Narrow',
'Hero',
'Restrain',
'Prejudice',
'Petal',
'Delighted',
'Borrow',
'Object',
'Innocent',
'Peculiar',
'Improvement',
'Forbid',
'Deal',
'Broken',
'Unusual',
'Senseless',
'Struggle',
'Elastic',
'Uneasy',
'Eccentric',
'Cheerful',
'Cartoon',
'Blur',
'Half',
'Grudge',
'Myth',
'Gradual',
'Immature',
'Telescope',
'Echo',
'Hometown',
'Confess',
'Mute',
'Absent',
'Laughter',
'Danger',
'Empty',
'Sigh',
'Curious',
'Exaggerate',
'Hesitate',
'Pause',
'Hurdle',
'Collector',
'Smile',
'Activity',
'Invitation',
'Subconscious',
'Dependable',
'Discovery',
'Necessary',
'Nice',
'Voice',
'Taste',
'Appease',
'Allow',
'Assume',
'Simple',
'Tradition',
'Conclusion',
'Justify',
'Notion',
'Sinister',
'Crude',
'Humiliated',
'Tickle',
'Experiment',
'Token',
'Rationing',
'Scraps',
'Crumb',
'Intense',
'Reception',
'Request',
'Number',
'Premonition',
'Psychic',
'Forgery',
'Stroke',
'Heretic',
'Ghost',
'Compass',
'Banquet',
'Addiction',
'Engagement',
'Race',
'Stroll',
'Catapult',
'Cannon',
'Envy',
'Bonsai',
'Cement',
'Diary',
'Memoir',
'Complaint',
'Pizza',
'Confident',
'Sympathy',
'Brave',
'Sandpit',
'Ball ',
'Treehouse',
'Energy',
'Liberate',
'Free',
'Streetlight',
'Bitter',
'Sour',
'Sweet',
'Model',
'Comedy',
'Disgust',
'Help',
'Earthquake',
'Scared',
'Victim',
'Pain',
'Grief',
'Mourning',
'Laundry',
'Wash',
'Corkscrew',
'Clock',
'Sandals',
'Belt',
'Skyscraper',
'Translate',
'Onion',
'Sunglasses',
'Spring',
'Desperate',
'Early',
'Incompetent',
'Lazy',
'Pogo',
'Chase',
'Appetite',
'Doppelganger',
'Picky',
'Scarf',
'Hoverboard',
'Levitate',
'Mirage',
'Skydive',
'Scuba',
'Greedy',
'Controversial',
'Nomad',
'Monk',
'Housewarming',
'Practice',
'Placebo',
'Barn',
'Camouflage',
'Gravity',
'Argument',
'Photocopy',
'Milk',
'Impulse',
'Fork',
'Cliche',
'Soup',
'Warmup',
'Manipulate',
'Gnome',
'Factory',
'Playground',
'Vintage',
'Jetlag',
'Skeleton',
'Sweat',
'Microphone',
'Flood',
'Pajamas',
'Windmill',
'Remake',
'History',
'Clever',
'Forget',
'Vegetarian',
'Meditate',
'Charity',
'Angel',
'Light',
'Revolution',
'Crash',
'Regret',
'Grandmother',
'Friendly',
'Hug',
'Salt',
'Takeout',
'Poison',
'Secret',
'Neighbour',
'Jealous',
'Lucky',
'Exhausted',
'Brick',
'Positive',
'Lawyer',
'Boast',
'Makeover',
'Lost',
'Sheepdog',
'River',
'Puddle',
'Promise',
'Popcorn',
'Servant',
'Wool',
'Brush',
'Kettle',
'Library',
'Receipt',
'Scissors',
'Refugee',
'Balloon',
'Crowd',
'Copy',
'Nostalgia',
'Glue',
'Cactus',
'Anchor',
'Dream',
'Surgery',
'Textbook',
'Incense',
'Flashlight',
'Battery',
'Billboard',
'Anniversary',
'Chainsaw',
'Bone',
'Headphones',
'Swing',
'Tupperware',
'Touchscreen',
'Recycle',
'Pandemic',
'Monopoly',
'Taboo',
'Ladder',
'Candy',
'Diplomat',
'Greenhouse',
'Applause',
'Nightmare',
'Election',
'Tournament',
'Museum',
'Farm',
'Pirate',
'Shrug',
'Beauty',
'Dragon',
'Backpack',
'Apology',
'Debate',
'Predator',
'Breakfast',
'Evolution',
'Molecule',
'Carpet',
'Mystery',
'Debt ',
'Test',
'Drums',
'Wave',
'Umbrella',
'Wine',
'Fantasy',
'Keyboard',
'Banana',
'Treasure',
'Map ',
'Coffee',
'Towel',
'Chess',
'Robot',
'Birthday',
'Bridge',
'Gamble',
'Beg',
'Celebrate',
'Alliance',
'Mature',
'Hammer',
'Respect',
'Revenge',
'Mistake',
'Random',
'Memory',
'Airport',
'Virus',
'Poet',
'Moat',
'Garden',
'Landslide',
'Jury',
'Support',
'Royalty',
'Sacred',
'Postcard',
'Cuddle',
'Camera',
'Helmet',
'Grass',
'Meditation',
'Sore',
'Break',
'Slippers',
'College',
'Peace',
'Perfection',
'Volume',
'Name',
'Pollution',
'Instinct',
'Fold',
'Sidewalk',
'Conductor',
'Dishwasher',
'Window',
'Around',
]

HARD_MATH_WORDS = [
"Differentiable",
"Differential",
"Integral",
"Quaternion",
"Sine",
"Cosine",
"Secant",
"Lagrange",
"Euclidean",
"Measure",
"Unbounded",
"Concatenate",
"Lebesgue",
"Hypercube",
"Operator",
"Vector",
"Eigenvalue",
"Trace",
"Theorem",
"Antiderivative",
"Denominator",
"Radian",
"Scalar",
"Parametric",
"Superposition",
"Hyperbola",
"Sequence",
"Convergent",
"Divergent",
"Abstraction"
]

MEDIUM_WORDS = [
    "time",
    "person",
    "year",
    "way",
    "day",
    "man",
    "world",
    "life",
    "hand",
    "part",
    "child",
    "eye",
    "woman",
    "place",
    "work",
    "week",
    "case",
    "point",
    "government",
    "company",
    "number",
    "group",
    "problem",
    "fact",
    "school",
    "state",
    "family",
    "member",
    "friend",
    "father",
    "power",
    "country",
    "night",
    "water",
    "home",
    "room",
    "mother",
    "area",
    "money",
    "story",
    "fact",
    "month",
    "lot",
    "right",
    "study",
    "book",
    "eye",
    "job",
    "word",
    "business",
    "issue",
    "side",
    "side",
    "kind",
    "head",
    "house",
    "service",
    "friend",
    "father",
    "power",
    "hour",
    "game",
    "line",
    "end",
    "member",
    "law",
    "car",
    "city",
    "community",
    "name",
    "president",
    "team",
    "minute",
    "idea",
    "kid",
    "body",
    "information",
    "back",
    "parent",
    "face",
    "others",
    "level",
    "office",
    "door",
    "health",
    "person",
    "art",
    "war",
    "history",
    "party",
    "result",
    "change",
    "morning",
    "reason",
    "research",
    "girl",
    "guy",
    "moment",
    "air",
    "teacher",
    "force",
    "education",
    "foot",
    "boy",
    "age",
    "policy",
    "process",
    "music",
    "market",
    "sense",
    "nation",
    "plan",
    "college",
    "interest",
    "death",
    "experience",
    "effect",
    "use",
    "class",
    "control",
    "field",
    "form",
    "event",
    "nature",
    "charge",
    "point",
    "home",
    "picture",
    "access",
    "treat",
    "range",
    "building",
    "seller",
    "court",
    "federal",
    "season",
    "society",
    "tax",
    "director",
    "position",
    "player",
    "record",
    "paper",
    "space",
    "ground",
    "form",
    "support",
    "event",
    "official",
    "whose",
    "matter",
    "everyone",
    "center",
    "couple",
    "site",
    "end",
    "project",
    "hit",
    "base",
    "activity",
    "star",
    "table",
    "court",
    "need",
    "far",
    "economy",
    "lot",
    "property",
    "stuff",
    "detail",
    "method",
    "sign",
    "financial",
    "fire",
    "future",
    "law",
    "action",
    "age",
    "bad",
    "industry",
    "worker",
    "whose",
    "simple",
    "quality",
    "pressure",
    "answer",
    "resource",
    "meeting",
    "disease",
    "success",
    "argument",
    "cup",
    "amount",
    "ability",
    "staff",
    "growth",
    "income",
    "marriage",
    "article",
    "region",
    "island",
    "exchange",
    "mind",
    "pay",
    "nation",
    "market",
    "value",
    "building",
    "skill",
    "woman",
    "captain",
    "guess",
    "necessary",
    "cloud",
    "object",
    "pocket",
    "temperature",
    "surprise",
    "poll",
    "budget",
    "degree",
    "popularity",
    "patient",
    "rule",
    "bridge",
    "option",
    "spend",
    "guard",
    "library",
    "dozen",
    "skin",
    "industry",
    "figure",
    "model",
    "source",
    "earth",
    "design",
    "surface",
    "button",
    "rank",
    "interview",
    "aspect",
    "average",
    "emergency",
    "fan",
    "speech",
    "impression",
    "essay",
    "responsibility",
    "attitude",
    "lab",
    "concern",
    "series",
    "individual",
    "film",
    "step",
    "industry",
    "mass",
    "card",
    "band",
    "roof",
    "bottom",
    "island",
    "advance",
    "conservative",
    "career",
    "culture",
    "potential",
    "immigrant",
    "choice",
    "feature",
    "street",
    "image",
    "partner",
    "budget",
    "discipline",
    "advice",
    "oil",
    "bite",
    "perception",
    "debate",
    "finding",
    "lake",
    "demand",
    "reputation",
    "structure",
    "sort",
    "database",
    "threat",
    "smile",
    "importance",
    "dispute",
    "tension",
    "variety",
    "sleep",
    "investment",
    "principle",
    "suggestion",
    "death",
    "airline",
    "library",
    "debt",
    "response",
    "shirt",
    "tradition",
    "tank",
    "nurse",
    "resolution",
    "debt",
    "meal",
    "reception",
    "worth",
    "security",
    "pension",
    "shower",
    "scheme",
    "punishment",
    "substance",
    "brand",
    "genre",
    "discount",
    "editor",
    "meter",
    "impression",
    "suit",
    "mixture",
    "bread",
    "channel",
    "discount",
    "minority",
    "works",
    "fishing",
    "drink",
    "suggestion",
    "accident",
    "faculty",
    "taste",
    "cheek",
    "celebration",
    "commission",
    "mode",
    "theory",
    "range",
    "industry",
    "deposit",
    "consultant",
    "continent",
    "enthusiasm",
    "marketing",
    "prince",
    "tissue",
    "debate",
    "sector",
    "sampling",
    "finance",
    "pleasure",
    "distinction",
    "sector",
    "liability",
    "concentration",
    "charity",
    "telephone",
    "behavior",
    "purchase",
    "planet",
    "ad",
    "costume",
    "negotiation",
    "agenda",
    "device",
    "actor",
    "finding",
    "count",
    "pleasure",
    "belly",
    "collection",
    "profession",
    "ambition",
    "essay",
    "challenge",
    "airport",
    "statistics",
    "electronics",
    "advisor",
    "spokesman",
    "promotion",
    "ridicule",
    "regime",
    "consultation",
    "enthusiasm" 
]

HOWITZER = [
    "howitzer",
    "azimuth",
    "aileron",
    "servo",
    "boson",
    "checksum",
    "gauss",
    "katana",
    "neodymium",
    "yakuza",
    "strafe",
    "parsec",
    "bushido"
]

TULLE = [
    "peplum",
    "tulle",
    "chignon",
    "bandeau",
    "freesia",
    "chenille",
    "kohl",
    "verbena",
    "doula",
    "ruche",
    "espadrille",
    "damask",
    "jacquard",
    "whipstich",
    "boucle",
    "taffeta",
    "sateen",
    "chambray",
    "voile"
]

US = [
    "manicotti",
    "ziti",
    "tilapia",
    "garbanzo",
    "kabob",
    "kwanza",
    "crawdad",
    "hibachi",
    "sandlot",
    "acetaminophen",
    "tamale",
    "kielbasa",
    "conniption",
    "tomatillo",
    "provolone",
    "albuterol",
    "staph",
    "goober",
    "luau"
]

UK = [
    "tippex",
    "biro",
    "tombola",
    "chipolata",
    "dodgem",
    "yob",
    "gazump",
    "abseil",
    "naff",
    "plaice",
    "judder",
    "chiropody",
    "korma",
    "bolshy",
    "quango",
    "pelmet",
    "brolly",
    "chaffinch",
    "escalope"
]

VERY_HARD_WORDS = [
    "abject",
    "aberration",
    "abjure",
    "abnegation",
    "abrogate",
    "abscond",
    "abstruse",
    "accede",
    "accost",
    "accretion",
    "acumen",
    "adamant",
    "admonish",
    "adumbrate",
    "adverse",
    "advocate",
    "affluent",
    "aggrandize",
    "alacrity",
    "alias",
    "ambivalent",
    "amenable",
    "amorphous",
    "anachronistic",
    "anathema",
    "annex",
    "antediluvian",
    "antiseptic",
    "apathetic",
    "antithesis",
    "apocryphal",
    "approbation",
    "arbitrary",
    "arboreal",
    "arcane",
    "archetypal",
    "arrogate",
    "ascetic",
    "aspersion",
    "assiduous",
    "atrophy",
    "bane",
    "bashful",
    "beguile",
    "bereft",
    "blandishment",
    "bilk",
    "bombastic",
    "cajole",
    "callous",
    "calumny",
    "camaraderie",
    "candor",
    "capitulate",
    "carouse",
    "carp",
    "caucus",
    "cavort",
    "circumlocution",
    "circumscribe",
    "circumvent",
    "clamor",
    "cleave",
    "cobbler",
    "cogent",
    "cognizant",
    "commensurate",
    "complement",
    "compunction",
    "concomitant",
    "conduit",
    "conflagration",
    "connive",
    "consign",
    "constituent",
    "construe",
    "contusion",
    "contrite",
    "contentious",
    "contravene",
    "convivial",
    "corpulence",
    "covet",
    "cupidity",
    "dearth",
    "debacle",
    "debauch",
    "debunk",
    "defunct",
    "demagogue",
    "denigrate",
    "derivative",
    "despot",
    "diaphanous",
    "didactic",
    "dirge",
    "disaffected",
    "discomfit",
    "disparate",
    "dispel",
    "disrepute",
    "divisive",
    "dogmatic",
    "dour",
    "duplicity",
    "duress",
    "eclectic",
    "edict",
    "ebullient",
    "egregious",
    "elegy",
    "elicit",
    "embezzlement",
    "emend",
    "emollient",
    "empirical",
    "emulate",
    "enervate",
    "enfranchise",
    "engender",
    "ephemeral",
    "epistolary",
    "equanimity",
    "equivocal",
    "espouse",
    "evanescent",
    "evince",
    "exacerbate",
    "exhort",
    "execrable",
    "exigent",
    "expedient",
    "expiate",
    "expunge",
    "extraneous",
    "extol",
    "extant",
    "expurgate",
    "fallacious",
    "fatuous",
    "fetter",
    "flagrant",
    "foil",
    "forbearance",
    "fortuitous",
    "fractious",
    "garrulous",
    "gourmand",
    "grandiloquent",
    "gratuitous",
    "hapless",
    "hegemony",
    "iconoclast",
    "idiosyncratic",
    "impecunious",
    "impetuous",
    "impinge",
    "impute",
    "inane",
    "inchoate",
    "incontrovertible",
    "incumbent",
    "inexorable",
    "inimical",
    "injunction",
    "inoculate",
    "insidious",
    "instigate",
    "insurgent",
    "interlocutor",
    "intimation",
    "inure",
    "invective",
    "intransigent",
    "inveterate",
    "irreverence",
    "knell",
    "laconic",
    "largesse",
    "legerdemain",
    "libertarian",
    "licentious",
    "linchpin",
    "litigant",
    "maelstrom",
    "maudlin",
    "maverick",
    "mawkish",
    "maxim",
    "mendacious",
    "modicum",
    "morass",
    "mores",
    "munificent",
    "multifarious",
    "nadir",
    "negligent",
    "neophyte",
    "noisome",
    "noxious",
    "obdurate",
    "obfuscate",
    "obstreperous",
    "officious",
    "onerous",
    "ostensible",
    "ostracism",
    "palliate",
    "panacea",
    "paradigm",
    "pariah",
    "partisan",
    "paucity",
    "pejorative",
    "pellucid",
    "penchant",
    "penurious",
    "pert",
    "pernicious",
    "pertinacious",
    "phlegmatic",
    "philanthropic",
    "pithy",
    "platitude",
    "plaudit",
    "plenitude",
    "plethora",
    "portent",
    "potentate",
    "preclude",
    "predilection",
    "preponderance",
    "presage",
    "probity",
    "proclivity",
    "profligate",
    "promulgate",
    "proscribe",
    "protean",
    "prurient",
    "puerile",
    "pugnacious",
    "pulchritude",
    "punctilious",
    "quaint",
    "quixotic",
    "quandary",
    "recalcitrant",
    "redoubtable",
    "relegate",
    "remiss",
    "reprieve",
    "reprobate",
    "rescind",
    "requisition",
    "rife",
    "sanctimonious",
    "sanguine",
    "scurrilous",
    "semaphore",
    "serendipity",
    "sobriety",
    "solicitous",
    "solipsism",
    "spurious",
    "staid",
    "stolid",
    "subjugate",
    "surfeit",
    "surreptitious",
    "swarthy",
    "tangential",
    "tome",
    "toady",
    "torpid",
    "travesty",
    "trenchant",
    "trite",
    "truculent",
    "turpitude",
    "ubiquitous",
    "umbrage",
    "upbraid",
    "utilitarian",
    "veracity",
    "vestige",
    "vicissitude",
    "vilify",
    "virtuoso",
    "vitriolic",
    "vituperate",
    "vociferous",
    "wanton",
    "winsome",
    "yoke",
    "zephyr",
    "wily",
    "tirade",
]

FICTIONAL_CHARACTERS = [
    "Sir Anthony Absolute",
    "The Rivals",
    "Nick Adams",
    "Parson Adams",
    "Joseph Andrews",
    "Frankie Addams",
    "Anthony Adverse",
    "Anthony Adverse",
    "Captain Ahab",
    "Moby Dick",
    "Albertine",
    "Remembrance of Things Past; or, In Search of Lost Time",
    "Alceste",
    "Algernon",
    "The Importance of Being Earnest",
    "Ali Baba",
    "Squire Allworthy",
    "Tom Jones",
    "Count Almaviva",
    "The Alvings",
    "Ghosts",
    "Amaryllis",
    "“Lycidas”",
    "Ananse",
    "Pamela Andrews",
    "Pamela",
    "Angelica",
    "Harry Angstrom",
    "Rabbit, Run",
    "Mr. and Mrs. Antrobus",
    "The Skin of Our Teeth",
    "Aramis",
    "Isabel Archer",
    "The Portrait of a Lady",
    "Enoch Arden",
    "Enoch Arden",
    "The Artful Dodger",
    "Oliver Twist",
    "Gustave von Aschenbach",
    "Death in Venice",
    "Lady Brett Ashley",
    "The Sun Also Rises",
    "Athos",
    "Ayesha",
    "She",
    "Dr. Aziz",
    "A Passage to India",
    "Baba-Yaga",
    "Babar",
    "Bilbo Baggins",
    "The Lord of the Rings",
    "Frodo Baggins",
    "The Lord of the Rings",
    "Harry Bailly",
    "The Canterbury Tales",
    "David Balfour",
    "Kidnapped",
    "Mr. Barkis",
    "David Copperfield",
    "Jake Barnes",
    "The Sun Also Rises",
    "Lily Bart",
    "The House of Mirth",
    "Yevgeny Bazarov",
    "Fathers and Sons",
    "Adam Bede",
    "Adam Bede",
    "Belial",
    "Paradise Lost",
    "Bennet family",
    "Pride and Prejudice",
    "Bertram family",
    "Mansfield Park",
    "Pierre Bezukhov",
    "War and Peace",
    "Big Brother",
    "Nineteen Eighty-four",
    "Big Daddy",
    "Cat on a Hot Tin Roof",
    "Rupert Birkin",
    "Women in Love",
    "Anthony Blanche",
    "Leopold Bloom",
    "Ulysses",
    "Molly Bloom",
    "Ulysses",
    "Bluebeard",
    "Tales of Mother Goose",
    "Bobbsey Twins",
    "William Boldwood",
    "Far from the Madding Crowd",
    "Bolkonsky family",
    "War and Peace",
    "James Bond",
    "Boojum",
    "The Hunting of the Snark",
    "The Borrowers",
    "Josiah Bounderby",
    "Hard Times",
    "Emma Bovary",
    "Madame Bovary",
    "Sally Bowles",
    "Lady Augusta Bracknell",
    "The Importance of Being Earnest",
    "Bradamante",
    "Matthew Bramble",
    "The Expedition of Humphry Clinker",
    "Colonel Brandon",
    "Sense and Sensibility",
    "Dave Brandstetter",
    "Fadeout",
    "Gudrun Brangwen",
    "Women in Love",
    "Ursula Brangwen",
    "Women in Love",
    "Brer Rabbit",
    "Brighella",
    "commedia dell’arte",
    "Hans Brinker",
    "Hans Brinker",
    "Lily Briscoe",
    "To the Lighthouse",
    "Dorothea Brooke",
    "Middlemarch",
    "Father Brown",
    "Bruin",
    "Tom and Daisy Buchanan",
    "The Great Gatsby",
    "Inspector Bucket",
    "Bleak House",
    "Buendía family",
    "Mr. Bumble",
    "Oliver Twist",
    "Natty Bumppo",
    "The Leatherstocking Tales",
    "Bunter",
    "Lord Peter Wimsey",
    "Billy Bunter",
    "Rhett Butler",
    "Gone with the Wind",
    "Camille",
    "Don Camillo",
    "Albert Campion",
    "Capitano",
    "commedia dell’arte",
    "Philip Carey",
    "Of Human Bondage",
    "Nick Carraway",
    "The Great Gatsby",
    "Richard Carstone",
    "Bleak House",
    "Nick Carter",
    "Sydney Carton",
    "A Tale of Two Cities",
    "Edward Casaubon",
    "Middlemarch",
    "Hans Castorp",
    "The Magic Mountain",
    "Cathbad",
    "Holden Caulfield",
    "The Catcher in the Rye",
    "Olive Chancellor",
    "The Bostonians",
    "Cheshire Cat",
    "Roger Chillingworth",
    "The Scarlet Letter",
    "Chingachgook",
    "The Leatherstocking Tales",
    "Mr. Chips",
    "Anna Christie",
    "Anna Christie",
    "Martin Chuzzlewit",
    "Martin Chuzzlewit",
    "John Claggart",
    "Billy Budd, Foretopman",
    "Angel Clare",
    "Claudine",
    "Claudine at School",
    "Arthur Clennam",
    "Little Dorrit",
    "Humphry Clinker",
    "The Expedition of Humphry Clinker",
    "Columbine",
    "commedia dell’arte",
    "Conan the Barbarian",
    "Conlaí",
    "Ulster cycle",
    "David Copperfield",
    "David Copperfield",
    "Richard Cory",
    "“Richard Cory”",
    "Corydon",
    "Mother Courage",
    "Ichabod Crane",
    "Cratchit family",
    "A Christmas Carol",
    "Janie Crawford",
    "Their Eyes Were Watching God",
    "Gerald Crich",
    "Women in Love",
    "Guy Crouchback",
    "Sword of Honour",
    "Robinson Crusoe",
    "Robinson Crusoe",
    "Cú Chulainn",
    "Ulster cycle",
    "Sergeant Cuff",
    "The Moonstone",
    "Cunégonde",
    "D’Artagnan",
    "Edmond Dantès",
    "The Count of Monte Cristo",
    "Fitzwilliam Darcy",
    "Pride and Prejudice",
    "Charles Darnay",
    "A Tale of Two Cities",
    "Dashwood family",
    "Sense and Sensibility",
    "Stephen Dedalus",
    "A Portrait of the Artist as a Young Man",
    "Ulysses",
    "Lady Honoria Dedlock",
    "Bleak House",
    "Madame Defarge",
    "A Tale of Two Cities",
    "Deirdre",
    "Ulster cycle",
    "Jean Des Esseintes",
    "Against the Grain",
    "Mr. Dick",
    "David Copperfield",
    "Digenis Akritas",
    "Arthur Dimmesdale",
    "The Scarlet Letter",
    "Dick and Nicole Diver",
    "Tender Is the Night",
    "Don Quixote",
    "Don Quixote",
    "Eliza Doolittle",
    "Pygmalion",
    "Lorna Doone",
    "Lorna Doone",
    "Dorothy",
    "Dottore",
    "commedia dell’arte",
    "Nancy Drew",
    "Edwin Drood",
    "The Mystery of Edwin Drood",
    "Bulldog Drummond",
    "Blanche DuBois",
    "A Streetcar Named Desire",
    "The Duchess",
    "The Duke and the Dauphin",
    "The Adventures of Huckleberry Finn",
    "Dulcinea",
    "Don Quixote",
    "C. Auguste Dupin",
    "Humphrey Chimpden Earwicker",
    "Finnegans Wake",
    "Eeyore",
    "Winnie-the-Pooh",
    "Elliot family",
    "Persuasion",
    "Lord Emsworth",
    "Enmerkar",
    "Henry Esmond",
    "The History of Henry Esmond, Esq.",
    "Till Eulenspiegel",
    "Bathsheba Everdene",
    "Far from the Madding Crowd",
    "Fagin",
    "Oliver Twist",
    "Lord Fauntleroy",
    "Little Lord Fauntleroy",
    "Jude Fawley",
    "Jude the Obscure",
    "Richard Feverel",
    "The Ordeal of Richard Feverel",
    "Fezziwig",
    "A Christmas Carol",
    "Flora Finching",
    "Little Dorrit",
    "Finn",
    "Fenian cycle",
    "Huckleberry Finn",
    "The Adventures of Huckleberry Finn",
    "Jeremiah Flintwinch",
    "Little Dorrit",
    "Phileas Fogg",
    "Around the World in Eighty Days",
    "Forsyte family",
    "The Forsyte Saga",
    "Count Fosco",
    "The Woman in White",
    "Frankenstein",
    "Frankenstein",
    "Ethan Frome",
    "Fu Manchu",
    "Hedda Gabler",
    "Hedda Gabler",
    "Sairey Gamp",
    "Martin Chuzzlewit",
    "Gandalf",
    "The Lord of the Rings",
    "Eugene Gant",
    "Look Homeward, Angel",
    "Of Time and the River",
    "Joe Gargery",
    "Great Expectations",
    "Jay Gatsby",
    "The Great Gatsby",
    "Gellert",
    "Beau Geste",
    "Beau Geste",
    "Gilgamesh",
    "Epic of Gilgamesh",
    "Glass family",
    "Franny and Zooey",
    "Boris Godunov",
    "Boris Godunov",
    "Golias",
    "Gollum",
    "The Lord of the Rings",
    "Père Goriot",
    "Le Père Goriot",
    "Gradgrind",
    "Hard Times",
    "Eugénie Grandet",
    "Eugénie Grandet",
    "Emmeline Grangerford",
    "The Adventures of Huckleberry Finn",
    "Dorian Gray",
    "The Picture of Dorian Gray",
    "Grendel",
    "Beowulf",
    "Clyde Griffiths",
    "An American Tragedy",
    "Grisette",
    "Titus Groan",
    "Mrs. Grundy",
    "Guermantes family",
    "Remembrance of Things Past; or, In Search of Lost Time",
    "Martin Guerre",
    "Remembrance of Things Past; or, In Search of Lost Time",
    "Guildenstern",
    "Hamlet",
    "Prince Hal",
    "Henry IV, Part I",
    "Henry V",
    "Mike Hammer",
    "Hardy Boys",
    "Jonathan Harker",
    "Dracula",
    "Harlequin",
    "commedia dell’arte",
    "Clarissa Harlowe",
    "Miss Havisham",
    "Great Expectations",
    "Jim Hawkins",
    "Treasure Island",
    "Asa and Sabbath Lily Hawks",
    "Wise Blood",
    "Headless horseman",
    "“The Legend of Sleepy Hollow”",
    "Heathcliff",
    "Wuthering Heights",
    "Uriah Heep",
    "David Copperfield",
    "Matt Helm",
    "Nora Helmer",
    "A Doll’s House",
    "Michael Henchard",
    "The Mayor of Casterbridge",
    "Herne the Hunter",
    "Henry Higgins",
    "Pygmalion",
    "Fanny Hill",
    "Fanny Hill",
    "Roy Hobbs",
    "The Natural",
    "Sherlock Holmes",
    "Horatio Hornblower",
    "Roderick Hudson",
    "Roderick Hudson",
    "Humbert Humbert",
    "Lolita",
    "Humpty Dumpty",
    "nursery rhyme",
    "Mr. Hyde",
    "The Strange Case of Dr. Jekyll and Mr. Hyde",
    "Iago",
    "Othello",
    "Ilya of Murom",
    "Infant Phenomenon",
    "Nicholas Nickleby",
    "Isolde",
    "Jabberwock",
    "Mr. Jaggers",
    "Great Expectations",
    "Jarndyce family",
    "Bleak House",
    "Dr. Jekyll",
    "The Strange Case of Dr. Jekyll and Mr. Hyde",
    "Mrs. Jellyby",
    "Bleak House",
    "Jim",
    "The Adventures of Huckleberry Finn",
    "Gulley Jimson",
    "The Horse’s Mouth",
    "Joad family",
    "The Grapes of Wrath",
    "Joseph K.",
    "The Trial",
    "Juliet",
    "Romeo and Juliet",
    "Karamazov brothers",
    "The Brothers Karamazov",
    "Anna Karenina",
    "Anna Karenina",
    "Katharina",
    "The Taming of the Shrew",
    "Carol Kennicott",
    "Main Street",
    "Diedrich Knickerbocker",
    "A History of New York",
    "George Knightley",
    "Emma",
    "Stanley Kowalski",
    "A Streetcar Named Desire",
    "Tonio Kröger",
    "Tonio Kröger",
    "Mr. Kurtz",
    "Heart of Darkness",
    "Will Ladislaw",
    "Middlemarch",
    "Lydia Languish",
    "The Rivals",
    "Silas Lapham",
    "The Rise of Silas Lapham",
    "Wolf Larsen",
    "The Sea Wolf",
    "Lazarillo de Tormes",
    "Lear",
    "King Lear",
    "Simon Legree",
    "Uncle Tom’s Cabin",
    "Lemminkäinen",
    "Inspector Lestrade",
    "Sherlock Holmes",
    "Konstantine Levin",
    "Anna Karenina",
    "Linton family",
    "Wuthering Heights",
    "Little Em’ly",
    "David Copperfield",
    "Little Eva",
    "Uncle Tom’s Cabin",
    "Little Nell",
    "The Old Curiosity Shop",
    "Lochinvar",
    "Lohengrin",
    "Parzival",
    "Willy Loman",
    "Death of a Salesman",
    "Studs Lonigan",
    "Studs Lonigan",
    "Lothario",
    "Robert Lovelace",
    "Sut Lovingood",
    "Lugalbanda",
    "Lulu",
    "Earth Spirit",
    "Pandora’s Box",
    "Arsène Lupin",
    "Tertius Lydgate",
    "Middlemarch",
    "Barry Lyndon",
    "Barry Lyndon",
    "Macbeth",
    "Macbeth",
    "Lady Macbeth",
    "Macbeth",
    "Macheath",
    "The Beggar’s Opera",
    "The Threepenny Opera",
    "Mad Hatter",
    "Madog ab Owain Gwynedd",
    "Maeldúin",
    "Abel Magwitch",
    "Great Expectations",
    "Jules Maigret",
    "Major Major",
    "Catch-22",
    "Malcolm",
    "Macbeth",
    "Alexander and Lucie Manette",
    "A Tale of Two Cities",
    "Marcel",
    "Remembrance of Things Past; or, In Search of Lost Time",
    "March Hare",
    "March family",
    "Little Women",
    "Augie March",
    "The Adventures of Augie March",
    "Marchmain family",
    "Jacob Marley",
    "A Christmas Carol",
    "Philip Marlowe",
    "Miss Marple",
    "Bertha Mason",
    "Jane Eyre",
    "Perry Mason",
    "Travis McGee",
    "Wilhelm Meister",
    "Wilhelm Meister’s Apprenticeship",
    "Oliver Mellors",
    "Mr. Merdle",
    "Little Dorrit",
    "Wilkins Micawber",
    "David Copperfield",
    "Daisy Miller",
    "Daisy Miller",
    "Miranda",
    "The Tempest",
    "Walter Mitty",
    "Mock Turtle",
    "Sara Monday",
    "Herself Surprised",
    "Moomintroll",
    "Hank Morgan",
    "A Connecticut Yankee in King Arthur’s Court",
    "Professor Moriarty",
    "Sherlock Holmes",
    "Catherine Morland",
    "Northanger Abbey",
    "Hazel Motes",
    "Wise Blood",
    "Mr. Moto",
    "Mowgli",
    "The Jungle Book",
    "Mugridge",
    "The Sea Wolf",
    "Baron Munchausen",
    "Edward Murdstone",
    "David Copperfield",
    "Captain Nemo",
    "Twenty Thousand Leagues Under the Sea",
    "The Mysterious Island",
    "Nicholas Nickleby",
    "Nicholas Nickleby",
    "Scarlett O’Hara",
    "Gone with the Wind",
    "Gabriel Oak",
    "Far from the Madding Crowd",
    "Oberon",
    "A Midsummer Night’s Dream",
    "Odette",
    "Remembrance of Things Past; or, In Search of Lost Time",
    "Duke of Omnium",
    "Palliser novels",
    "Anthony Trollope",
    "Eugene Onegin",
    "Ophelia",
    "Hamlet",
    "Orlando",
    "As You Like It",
    "Orlando",
    "Gilbert Osmond",
    "The Portrait of a Lady",
    "Othello",
    "Othello",
    "Palliser family",
    "Palliser novels",
    "Anthony Trollope",
    "Pancks",
    "Little Dorrit",
    "Pangloss",
    "Pantaloon",
    "commedia dell’arte",
    "Panurge",
    "Gargantua and Pantagruel ",
    "Peachum family",
    "The Beggar’s Opera",
    "The Threepenny Opera",
    "Pearl",
    "The Scarlet Letter",
    "Seth Pecksniff",
    "Martin Chuzzlewit",
    "Pedrolino",
    "commedia dell’arte",
    "Peer Gynt",
    "Peer Gynt)",
    "Clara Peggotty",
    "David Copperfield",
    "Peter Pan",
    "Peter Pan",
    "Petruchio",
    "The Taming of the Shrew",
    "Samuel Pickwick",
    "The Pickwick Papers",
    "Piglet",
    "Winnie-the-Pooh",
    "Billy Pilgrim",
    "Slaughterhouse-Five",
    "Pinocchio",
    "Pip",
    "Great Expectations",
    "Sir Fretful Plagiary",
    "The Critic",
    "Anna Livia Plurabelle",
    "Finnegans Wake",
    "Hercule Poirot",
    "Ross Poldark",
    "Aunt Polly",
    "Pollyanna",
    "Polonius",
    "Hamlet",
    "Pontifex family",
    "The Way of All Flesh",
    "Mary Poppins",
    "Porthos",
    "Portia",
    "The Merchant of Venice",
    "Harry Potter",
    "Fanny Price",
    "Mansfield Park",
    "Miss Prism",
    "The Importance of Being Earnest",
    "Prospero",
    "The Tempest",
    "J. Alfred Prufrock",
    "Hester Prynne",
    "The Scarlet Letter",
    "Puck",
    "A Midsummer Night’s Dream",
    "Puss in Boots",
    "Quasimodo",
    "The Hunchback of Notre Dame",
    "Allan Quatermain",
    "King Solomon’s Mines",
    "Captain Queeg",
    "The Caine Mutiny",
    "Queen of Hearts",
    "Queequeg",
    "Moby Dick",
    "Adela Quested",
    "A Passage to India",
    "Daniel Quilp",
    "The Old Curiosity Shop",
    "A.J. Raffles",
    "Ramsay family",
    "To the Lighthouse",
    "Basil Ransom",
    "The Bostonians",
    "Rodion Raskolnikov",
    "Crime and Punishment",
    "Red Cross Knight",
    "The Faerie Queene",
    "Regan",
    "King Lear",
    "Reynard the Fox",
    "Richard III",
    "Henry VI, Part 2",
    "Henry VI, Part 3",
    "Richard III",
    "Tom Ripley",
    "Howard Roark",
    "The Fountainhead",
    "Robin Hood",
    "Christopher Robin",
    "Winnie-the-Pooh",
    "Mr. Rochester",
    "Jane Eyre",
    "Rocinante",
    "Don Quixote",
    "Romeo",
    "Romeo and Juliet",
    "Rosalind",
    "As You Like It",
    "Rosencrantz",
    "Hamlet",
    "Rostov family",
    "War and Peace",
    "Roxane",
    "Cyrano de Bergerac",
    "Barnaby Rudge",
    "Barnaby Rudge",
    "Ruggiero",
    "Marmaduke Ruggles",
    "Horace Rumpole",
    "Charles Ryder",
    "The Saint",
    "Gregor Samsa",
    "The Metamorphosis",
    "Sancho Panza",
    "Don Quixote",
    "Tom Sawyer",
    "Scapin",
    "commedia dell’arte",
    "Scaramouche",
    "commedia dell’arte",
    "Ebenezer Scrooge",
    "A Christmas Carol",
    "Amelia Sedley",
    "Vanity Fair",
    "The Shadow",
    "Shakuntala",
    "The Recognition of Shakuntala",
    "Becky Sharp",
    "Vanity Fair",
    "Ántonia Shimerda",
    "My Ántonia",
    "Anne Shirley",
    "Shrek",
    "Shylock",
    "The Merchant of Venice",
    "Bill Sikes",
    "Oliver Twist",
    "Long John Silver",
    "Treasure Island",
    "Tyrone Slothrop",
    "Gravity’s Rainbow",
    "Smike",
    "Nicholas Nickleby",
    "George Smiley",
    "Winston Smith",
    "Nineteen Eighty-four",
    "Snark",
    "“The Hunting of the Snark”",
    "Snopes family",
    "The Hamlet",
    "Snowball",
    "Animal Farm",
    "Lucy Snowe",
    "Villette",
    "Halvard Solness",
    "The Master Builder",
    "Hetty Sorrel",
    "Adam Bede",
    "Sam Spade",
    "The Maltese Falcon",
    "Dora Spenlow",
    "David Copperfield",
    "Wackford Squeers",
    "Nicholas Nickleby",
    "Stage Manager",
    "Our Town",
    "Monroe Stahr",
    "The Last Tycoon",
    "Starbuck",
    "Moby Dick",
    "Willie Stark",
    "All the King’s Men",
    "James Steerforth",
    "David Copperfield",
    "Lambert Strether",
    "Esther Summerson",
    "Bleak House",
    "Charles and Joseph Surface",
    "The School for Scandal",
    "Sutpen family",
    "Svengali",
    "Trilby",
    "Charles Swann",
    "Remembrance of Things Past; or, In Search of Lost Time",
    "Verena Tarrant",
    "The Bostonians",
    "Tarzan",
    "Tattycoram",
    "Little Dorrit",
    "Suky Tawdry",
    "The Threepenny Opera",
    "Lady Teazle",
    "The School for Scandal",
    "William Tell",
    "Becky Thatcher",
    "Thomas Bigger",
    "Native Son",
    "Thomas the Tank Engine",
    "Sadie Thompson",
    "Christopher Tietjens",
    "Parade’s End",
    "Tinker Bell",
    "Peter Pan",
    "Titania",
    "A Midsummer Night’s Dream",
    "Tituba",
    "The Crucible",
    "Topsy",
    "Uncle Tom’s Cabin",
    "Tristan",
    "Betsey Trotwood",
    "David Copperfield",
    "Sergeant Francis Troy",
    "Far from the Madding Crowd",
    "Tweedledum and Tweedledee",
    "Oliver Twist",
    "Oliver Twist",
    "Uncle Tom",
    "Uncle Tom’s Cabin",
    "Urizen",
    "Jean Valjean",
    "Les Misérables",
    "Valmont",
    "Dangerous Liaisons",
    "Philo Vance",
    "Dolly Varden",
    "Barnaby Rudge",
    "Varner family",
    "The Hamlet",
    "Diggory Venn",
    "The Return of the Native",
    "Captain Vere",
    "Billy Budd, Foretopman",
    "Rosamond Vincy",
    "Middlemarch",
    "Viola",
    "Twelfth Night",
    "Count Aleksey Vronsky",
    "Anna Karenina",
    "Eustacia Vye",
    "The Return of the Native",
    "Dr. Watson",
    "Sherlock Holmes",
    "Weird Sisters",
    "Macbeth",
    "Sam Weller",
    "The Pickwick Papers",
    "Frederick Wentworth",
    "Persuasion",
    "Werther",
    "The Sorrows of Young Werther",
    "Sophia Western",
    "Tom Jones",
    "Simon Wheeler",
    "White Rabbit",
    "Agnes Wickfield",
    "David Copperfield",
    "Tom Wilcher",
    "To Be a Pilgrim",
    "Damon Wildeve",
    "The Return of the Native",
    "Pudd’nhead Wilson",
    "Pudd’nhead Wilson",
    "Lord Peter Wimsey",
    "Wingfield family",
    "The Glass Menagerie",
    "Wise Men of Gotham",
    "Wolfdietrich",
    "Nero Wolfe",
    "Fer-de-Lance",
    "Emma Woodhouse",
    "Emma",
    "Bertie Wooster",
    "Clym Yeobright",
    "The Return of the Native",
    "Captain John Yossarian",
    "Catch-22",
    "Zorro",
]

FAMOUS_HISTORICAL_FIGURES = [
    "Alexander the Great",
    "Napoleon Bonaparte",
    "Christopher Columbus",
    "Winston Churchill",
    "Queen Elizabeth I",
    "Leonardo da Vinci",
    "Thomas Edison",
    "Albert Einstein",
    "Henry VIII",
    "Queen Victoria",
    "Genghis Khan",
    "Martin Luther",
    "Julius Caesar",
    "Mahatma Gandhi",
    "George Washington",
    "Adolf Hitler",
    "Abraham Lincoln",
    "John F. Kennedy",
    "Charlemagne",
    "William the Conqueror",
    "Confucius",
    "Queen Cleopatra",
    "Saint Paul",
    "Martin Luther King Jr.",
    "Buddha",
    "Johann Sebastian Bach",
    "Isaac Newton",
    "Archimedes",
    "Galileo Galilei",
    "Aristotle",
    "Plato",
    "Socrates",
    "Homer",
    "Alexander Graham Bell",
    "Louis Pasteur",
    "Nikola Tesla",
    "Charles Darwin",
    "Rene Descartes",
    "James Watt",
    "Karl Marx",
    "Friedrich Nietzsche",
    "Sigmund Freud",
    "Immanuel Kant",
    "Adam Smith",
    "Voltaire",
    "Johann Wolfgang von Goethe",
    "Beethoven",
    "Mozart",
    "Chopin",
    "Tchaikovsky",
    "Shakespeare",
    "Marlon Brando",
    "Marilyn Monroe",
    "Audrey Hepburn",
    "Princess Diana",
    "Queen Mother",
    "Queen Elizabeth II",
    "Pope John Paul II",
    "Pope Francis",
    "Martin Luther King Jr.",
    "Mahatma Gandhi",
    "Nelson Mandela",
    "George Washington",
    "Abraham Lincoln",
    "Franklin D. Roosevelt",
    "John F. Kennedy",
    "Ronald Reagan",
    "Barack Obama",
    "Marie Curie",
    "Albert Schweitzer",
    "Jane Goodall",
    "Malala Yousafzai",
    "Mother Teresa",
    "Rosa Parks",
    "Harriet Tubman",
    "Amelia Earhart",
    "Florence Nightingale",
    "Eleanor Roosevelt",
    "Susan B. Anthony",
    "Sojourner Truth",
    "Walt Disney",
    "Steve Jobs",
    "Mark Zuckerberg",
    "Elon Musk",
    "Bill Gates",
    "Warren Buffett",
    "Oprah Winfrey",
    "Michael Jordan",
    "Lionel Messi",
    "Cristiano Ronaldo",
    "Pele",
    "Diego Maradona",
    "Muhammad Ali",
    "Usain Bolt",
    "Serena Williams",
    "Simone Biles",
    "Michael Phelps",
    "LeBron James",
    "Kobe Bryant",
    "Shaquille O'Neal",
    " Magic Johnson",
    "Larry Bird",
    "Charles Barkley",
    "John Lennon",
    "Paul McCartney",
    "George Harrison",
    "Ringo Starr",
    "Jimi Hendrix",
    "Janis Joplin",
    "Jim Morrison",
    "Kurt Cobain",
    "Elvis Presley",
    "Michael Jackson",
    "Madonna",
    "Prince",
    "Whitney Houston",
    "Beyonce",
    "Bruce Springsteen",
    "Bob Dylan",
    "Mick Jagger",
    " Freddie Mercury",
    "Axl Rose",
    "Ozzy Osbourne",
    "Sid Vicious",
    "Johnny Rotten",
    "Keith Richards",
    "Pablo Picasso",
    "Vincent van Gogh",
    "Salvador Dali",
    "Rembrandt",
    "Leonardo da Vinci",
    "Michelangelo",
    "Raphael",
    "Jan van Eyck",
    "Gustav Klimt",
    "Henri Matisse",
    "Edvard Munch",
    "Frida Kahlo",
    "Georgia O'Keeffe",
    "Andy Warhol",
    "Roy Lichtenstein",
    "Piet Mondrian",
    "Jackson Pollock",
    "Mark Rothko",
    "Johannes Vermeer",
    "Gustave Courbet",
    "Eugene Delacroix",
    "Pierre-Auguste Renoir",
    "Edgar Degas",
    "Camille Pissarro",
    "Mary Cassatt",
    "Henri Cartier-Bresson",
    "Ansel Adams",
    "Dorothea Lange",
    "Richard Avedon",
    "Isaac Newton",
    "Galileo Galilei",
    "Nikola Tesla",
    "Thomas Edison",
    "Alexander Graham Bell",
    "Henry Ford",
    "Wright Brothers",
    "Gutenberg",
    "Neil Armstrong",
    "Buzz Aldrin",
    "Michael Collins",
    "Charles Lindbergh",
    "Orville Wright",
    "Wilbur Wright",
    "Amelia Earhart",
    "Jacques Cousteau",
    "Neil deGrasse Tyson",
    "Stephen Hawking",
    "Sigmund Freud",
    "Carl Jung",
    "Freud",
    "Jung",
    "Einstein",
    "Marie Curie",
    "Rosalind Franklin",
    "Grace Hopper",
    "Ada Lovelace",
    "Alan Turing",
    "John von Neumann",
    "Tim Berners-Lee",
    "Linus Torvalds",
    "Steve Wozniak",
    "Bill Joy",
    "Larry Page",
    "Sergey Brin",
    "Elon Musk",
    "Mark Zuckerberg",
    "Jack Ma",
    "Larry Ellison",
    "Satoshi Nakamoto",
    "Charles Babbage",
    "Gottfried Wilhelm Leibniz",
    "Blaise Pascal",
    "John Locke",
    "René Descartes",
    "Baruch Spinoza",
    "Gottfried Wilhelm Leibniz",
    "Immanuel Kant",
    "Johann Wolfgang von Goethe",
    "Friedrich Nietzsche",
    "Søren Kierkegaard",
    "Friedrich Hegel",
    "Karl Marx",
    "Adam Smith",
    "John Stuart Mill",
    "Ayn Rand",
    "Jean-Jacques Rousseau",
    "Voltaire",
    "Bertrand Russell",
    "Noam Chomsky",
    "Alan Greenspan",
    "Paul Krugman",
    "John Maynard Keynes",
    "Milton Friedman",
    "Friedrich Hayek",
    "Thomas Malthus",
    "David Ricardo",
    "Joseph Stiglitz",
    "Amartya Sen",
    "Nassim Nicholas Taleb",
    "Daniel Kahneman",
    "Richard Thaler",
    "Jordan Peterson",
    "Sam Harris",
    "Brené Brown",
    "Malcolm Gladwell",
    "Sapiens",
    "Yuval Noah Harari",
    "Daniel Dennett",
    "Stephen Pinker",
    "Jonathan Haidt",
    "Alain de Botton",
    "Shawn Achor",
    "Angela Duckworth",
    "Atul Gawande",
    "Barry Schwartz",
    "Dan Ariely",
    "Daniel Pink",
    "David and Chip Heath",
    "David Brooks",
    "David Eagleman",
    "David Grann",
    "David Halberstam",
    "David Rosenhan",
    "Elizabeth Gilbert",
    "Gretchen Rubin",
    "James Clear",
    "James Gleick",
    "James Surowiecki",
]        

CHARACTER_WORDS = [*FICTIONAL_CHARACTERS, *FAMOUS_HISTORICAL_FIGURES]

DEFAULT_WORDS = MEDIUM_WORDS